### ISSUE TITLE
Idea: Config for including/excluding specific projects/directories by path/glob

### ISSUE THREAD

**Issue by Nezteb** [kamranahmedse/git-standup#130]
Currently running `git standup` in a directory of git repos shows previous-day commits in every subdirectory. I would like a way to configure this behavior, almost like a global `.gitstandupignore` or something.

`git standup` can still only operate on the current directory and subdirectories, but I'd like to be able to filter directories by their name or path.

Example config:
```toml
[projects]

# Default to process includes first
process_includes_first = true

includes = [
  # All git projects
  "~/Git",
  # Or select projects
  "~/Git/oss_project_1"
]

excludes = [
  # Exclude a specific project
  "~/Git/side_project_1",
  # Exclude any git projects in the home directory
  "~",
  # Exclude any directory named 'node_modules'
  "node_modules"
]
```
